## num - numerical
## py- python

## numpy

In [1]:
import numpy as np

In [2]:
sample_list=[6,22,24]

In [4]:
np.array(sample_list)

array([ 6, 22, 24])

In [5]:
arr=np.array([22,3,6 ])
arr

array([22,  3,  6])

In [6]:
list_of_lists=[[22,25,8],[13,12,10],[77,90,6]]
np.array(list_of_lists)

array([[22, 25,  8],
       [13, 12, 10],
       [77, 90,  6]])

In [7]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.zeros(30)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.zeros(100,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((10,50))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 

In [14]:
np.ones(100,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
import numpy as np

In [16]:
np.linspace(0,15,2)

array([ 0., 15.])

## 2 is for 2 output will be printed 

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## it will print the 4 rows with 7 colunm and everytime we run this program it will print a randaom number ranging from 0-9

In [18]:
np.random.rand(4,7)

array([[0.13454727, 0.10201382, 0.55387761, 0.5901144 , 0.7955204 ,
        0.24801796, 0.62814433],
       [0.86320543, 0.17600906, 0.62462593, 0.9274572 , 0.30992427,
        0.09606835, 0.31945974],
       [0.27740878, 0.18731479, 0.40134342, 0.96989207, 0.26953892,
        0.86978151, 0.71433956],
       [0.09018829, 0.48480098, 0.28958195, 0.16699633, 0.60679661,
        0.75924471, 0.11564645]])

In [19]:
np.random.randn(3,2)

array([[-0.44066968, -0.99988689],
       [-0.27462458, -1.48773863],
       [-0.24743709,  1.61668531]])

In [21]:
np.random.randint(44,100)

78

## it will select random number between 44 - 100

In [23]:
np.random.randint(24,70,100)

array([45, 52, 28, 68, 33, 42, 42, 35, 69, 53, 34, 30, 35, 44, 25, 53, 43,
       37, 58, 54, 49, 28, 27, 25, 61, 31, 32, 38, 27, 65, 33, 27, 66, 52,
       55, 53, 33, 58, 50, 40, 32, 46, 52, 55, 48, 29, 61, 38, 46, 40, 30,
       65, 36, 39, 35, 39, 31, 69, 46, 58, 29, 42, 56, 60, 55, 57, 50, 33,
       40, 51, 30, 48, 56, 33, 39, 60, 62, 38, 48, 67, 68, 29, 68, 62, 47,
       55, 57, 55, 62, 49, 67, 62, 33, 67, 40, 28, 52, 54, 55, 60])

## it will print 24-70 with 100 output

In [34]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [26]:
rand_array=np.random.randint(0,100,4)
rand_array

array([ 5, 69, 60, 96])

In [27]:
sample_array.reshape(5,4) 

ValueError: cannot reshape array of size 39 into shape (5,4)

In [28]:
## because there are only 39 elemnts so we cant use 5,4

In [35]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [36]:
rand_array.min()

5

In [37]:
rand_array.argmin()

0

## it will return the index of the minimum number

In [38]:
sample_array.dtype

dtype('int32')

In [39]:
a=np.eye(6)

In [40]:
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [41]:
a=np.random.rand(2,3)
a

array([[0.0826983 , 0.30368135, 0.08862908],
       [0.14557265, 0.94242506, 0.65025511]])

In [42]:
a.T

array([[0.0826983 , 0.14557265],
       [0.30368135, 0.94242506],
       [0.08862908, 0.65025511]])

## t-> transpose rows into columns n col into rows

In [44]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [45]:
sample_array[3]

13

In [46]:
sample_array[3:7]

array([13, 14, 15, 16])

## slicing  7 will not be consider

In [49]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [52]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [53]:
subset_sample_array=sample_array[0:7]

In [54]:
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [55]:
subset_sample_array[1:4]=1001

In [56]:
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [57]:
subset_sample_array[:]=1001

In [58]:
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])